const products = [
    {
      id: 0,
      title: 'i3 12100',
      description: 'Procesador mid-level de Intel',
      price: '$129.99',
      old_price: '',
      image: '/assets/i3.webp',
      stock: 14,
      free_shipping: false,
      brand: 'Intel',
      category: 'Procesadores',
    },
    {
      id: 1,
      title: 'i5 12400F',
      description: 'Procesador mid-level de Intel',
      price: '$174.99',
      old_price: '$199.99',
      image: '/assets/i5.webp',
      stock: 6,
      free_shipping: true,
      brand: 'Intel',
      category: 'Procesadores',
    },
    {
      id: 2,
      title: 'i7 12700',
      description: 'Procesador high-level de Intel',
      price: '$329.99',
      old_price: '$349.99',
      image: '/assets/i7.webp',
      stock: 4,
      free_shipping: true,
      brand: 'Intel',
      category: 'Procesadores',
    },
    {
      id: 3,
      title: 'Ryzen 9 5900x',
      description: 'Procesador high-level de AMD',
      price: '$349.99',
      old_price: '',
      image: '/assets/ryzen95900x.webp',
      stock: 8,
      free_shipping: false,
      brand: 'AMD',
      category: 'Procesadores',
    },
    {
      id: 4,
      title: 'Ryzen 9 5600x',
      description: 'Procesador mid-level de AMD',
      price: '$249.99',
      old_price: '$299.99',
      image: '/assets/ryzen55600x.webp',
      stock: 17,
      free_shipping: false,
      brand: 'AMD',
      category: 'Procesadores',
    }
  ];

  export default products